services:

  db:
    restart: always
    image: "mysql:8.0"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "${MYSQL_PASS}"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  django-media:
  django-static:
  mysql-data:
  redis-data:
